version: "3.8"
services:
  nuxeo:
    image: nuxeo-custom-operation-validate-document:1.0.0
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      NUXEO_DEV: "true"
      NUXEO_PACKAGES: nuxeo-web-ui
      NUXEO_CLID: ""
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
volumes:
  data: {}
